server:
  port: 9090
  servlet:
    context-path: /care
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:animalcaredatabase;MODE=PostgreSQL
    username: a
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
